"use client";
import { motion } from "framer-motion";
import { Bot, Inbox, ShieldAlert, UserCheck } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { cn } from "@/lib/format";

export function PageHeader({ title, subtitle, eyebrow, actions }: { title: string; subtitle?: string; eyebrow?: string; actions?: React.ReactNode }) {
  return (
    <motion.div initial={{ opacity: 0, y: 4 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.18 }} className="mb-6 flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
      <div>
        {eyebrow && <p className="eyebrow mb-3">{eyebrow}</p>}
        <h1 className="font-display text-2xl font-semibold tracking-tight text-white md:text-[28px]">{title}</h1>
        {subtitle && <p className="mt-1.5 max-w-3xl text-sm text-slate-400 md:text-[15px]">{subtitle}</p>}
      </div>
      {actions && <div className="flex flex-wrap gap-2">{actions}</div>}
    </motion.div>
  );
}

export function Tabs<T extends string>({ tabs, value, onChange, className }: { tabs: readonly T[] | { id: T; label: string; count?: number }[]; value: T; onChange: (v: T) => void; className?: string }) {
  const items = (tabs as (T | { id: T; label: string; count?: number })[]).map((t) => (typeof t === "string" ? { id: t, label: t } : t)) as { id: T; label: string; count?: number }[];
  return (
    <div role="tablist" className={cn("flex flex-wrap gap-1 rounded-xl border border-white/[0.07] bg-ink-900/60 p-1", className)}>
      {items.map((t) => (
        <button
          key={t.id} role="tab" aria-selected={value === t.id} onClick={() => onChange(t.id)}
          className={cn("focus-ring relative rounded-lg px-3 py-1.5 text-sm transition-colors duration-100", value === t.id ? "text-white" : "text-slate-400 hover:text-slate-200")}
        >
          {value === t.id && <span className="absolute inset-0 rounded-lg bg-setu-500/15 ring-1 ring-setu-400/30" />}
          <span className="relative">{t.label}{t.count !== undefined && <span className="ml-1.5 text-xs text-slate-500">{t.count}</span>}</span>
        </button>
      ))}
    </div>
  );
}

export function EmptyState({ title, body, icon: Icon = Inbox, action }: { title: string; body?: string; icon?: LucideIcon; action?: React.ReactNode }) {
  return (
    <div className="flex flex-col items-center justify-center rounded-2xl border border-dashed border-white/10 px-6 py-14 text-center">
      <div className="grid h-12 w-12 place-items-center rounded-2xl bg-setu-500/10 text-setu-300 ring-1 ring-setu-400/20"><Icon className="h-6 w-6" /></div>
      <p className="mt-4 font-display text-base font-semibold text-white">{title}</p>
      {body && <p className="mt-1 max-w-sm text-sm text-slate-400">{body}</p>}
      {action && <div className="mt-5">{action}</div>}
    </div>
  );
}

export function Skeleton({ className }: { className?: string }) {
  return (
    <div className={cn("relative overflow-hidden rounded-lg bg-white/[0.05]", className)}>
      <div className="absolute inset-0 -translate-x-full animate-shimmer bg-gradient-to-r from-transparent via-white/[0.06] to-transparent" />
    </div>
  );
}

/** The "AI recommends — humans decide" banner. Use on every AI-generated surface. */
export function AIDisclaimer({ variant = "ai", className, children }: { variant?: "ai" | "human"; className?: string; children?: React.ReactNode }) {
  const ai = variant === "ai";
  const Icon = ai ? Bot : UserCheck;
  return (
    <div className={cn("flex items-start gap-3 rounded-xl border px-4 py-3 text-sm", ai ? "border-ai-400/25 bg-ai-500/[0.07] text-ai-300" : "border-saffron-400/30 bg-saffron-500/[0.07] text-saffron-300", className)}>
      <Icon className="mt-0.5 h-5 w-5 shrink-0" />
      <div>
        <p className="font-semibold tracking-wide">{ai ? "AI RECOMMENDATION — NOT FINAL DECISION" : "HUMAN DECISION REQUIRED"}</p>
        <p className="mt-0.5 text-slate-300/80">
          {children ?? (ai
            ? "Generated by StartupSetu AI agents for human review. AI cannot select a startup, sign a contract or release money."
            : "Final decisions on selection, contracts and payments are made by authorised officers and experts.")}
        </p>
      </div>
    </div>
  );
}

export function Alert({ tone = "warning", title, children, icon: Icon = ShieldAlert }: { tone?: "warning" | "error" | "info" | "success"; title: string; children?: React.ReactNode; icon?: LucideIcon }) {
  const t = { warning: "border-warn-400/30 bg-warn-500/[0.07] text-warn-400", error: "border-danger-400/30 bg-danger-500/[0.07] text-danger-400", info: "border-setu-400/30 bg-setu-500/[0.07] text-setu-300", success: "border-mint-400/30 bg-mint-500/[0.07] text-mint-400" }[tone];
  return (
    <div className={cn("flex items-start gap-3 rounded-xl border px-4 py-3 text-sm", t)} role="alert">
      <Icon className="mt-0.5 h-5 w-5 shrink-0" />
      <div><p className="font-semibold">{title}</p>{children && <div className="mt-0.5 text-slate-300/80">{children}</div>}</div>
    </div>
  );
}

export function DemoBadge({ className }: { className?: string }) {
  return (
    <span className={cn("inline-flex items-center gap-1.5 rounded-full border border-saffron-400/30 bg-saffron-500/10 px-2.5 py-1 text-[11px] font-medium tracking-wide text-saffron-300", className)}>
      <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-saffron-400" />
      StartupSetu
    </span>
  );
}

export function Field({ label, children, hint }: { label: string; children: React.ReactNode; hint?: string }) {
  return (
    <label className="block">
      <span className="mb-1.5 block text-sm font-medium text-slate-300">{label}</span>
      {children}
      {hint && <span className="mt-1 block text-xs text-slate-500">{hint}</span>}
    </label>
  );
}
